### ISSUE TITLE
Can this be compattible with nette/latte?

### ISSUE THREAD

**Issue by nikola-wd** [netflie/componentes#3]
Hi, this looks awesome at first glance. Really what I've been searching for, but I have a few questions.

I am focusing on coding  custom WordPress websites with a framework that I created. I am coding Gutenberg Blocks which by default should be written as a PHP string. That's why I made use of the nette/latte for really simple templating. So, I already use a compiler that compiles from latte templates to a PHP string that Gutenberg blocks need as the end result. Do you think there is a way to implement your solution inside a latte template? My guess is no because your solution also needs a compiler, or I am mistaken? 

I would use it for something like this, for example: 

Instead of writing: 

```
{include 'partials/button',
  obj: ['title' => 'title', 'new_tab' => true]
}
```

I would write something like this: 
`<custom-btn obj={$obj}></custom-btn>`

I know about lit and web components but I am not sure how it might affect SEO.

Thanks in advance

**Comment by aalbarca** [comment]
Hi @nikola-wd!

Well, you can compiler your HTML code in multiple steps. You only need to create a Compiler Wrap class:

```<?php

class OwnCompiler
{
    public function compile(string $html): string
    {
        $compiled = $this->compilerOne($html);
        $compiled = $this->compileTwo($compiled);
        $compiled = $this->compileNetflieComponents($compiled);

        return $compiled;
    }

    private function compileNetflieComponents(string $input_html): string
    {
        $viewPath = realpath(__DIR__ . '/views'); // your project views folder
        $componentes = Componentes::create($viewPath);

        return $componentes->render($input_html);
    }
}```

Best regards,
Álex.
